# Generated by Django 3.2.9 on 2021-11-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=12)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cpu_hardware_id', models.CharField(max_length=40)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepoModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('git_repo', models.CharField(max_length=240)),
                ('git_commit', models.CharField(max_length=240)),
                ('git_username', models.CharField(max_length=240)),
                ('upvotes', models.PositiveIntegerField(default=0)),
                ('downvotes', models.PositiveIntegerField(default=0)),
                ('discussion_url', models.URLField(blank=True, max_length=240, null=True)),
                ('signed_off', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stars', models.PositiveIntegerField(default=0)),
                ('module_name', models.CharField(max_length=40, null=True)),
                ('module_version', models.CharField(max_length=40, null=True)),
            ],
        ),
    ]
