# Generated by Django 3.2.9 on 2021-11-27 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contributor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repomodel',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributor_to_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platforms',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_to_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='platforms',
            name='repo_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_to_repository', to='contributor.repomodel'),
        ),
        migrations.AddField(
            model_name='devices',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_to_contributor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devices',
            name='repo_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_to_repository', to='contributor.repomodel'),
        ),
    ]
